// __NAME__ - SAMD21 app (generated by samd-new - edit freely)
//
// Reset_Handler (startup.cpp) runs chip.init() (48 MHz DFLL, USB CDC
// serial, 1 ms SysTick) before calling setup(), then loops loop() forever.
//
// Pin API (compile-time checks, chainable):
//   chip.PA10.use_out();  chip.PA08.use_pwm(1000).duty(0.5f);
//   chip.PA05.use_adc().adc_read();
// Periodic work:  chip.scheduler.every(ms, fn) + chip.scheduler.tick() in loop().
// Printing:       Serial.printf("x = %.2f\n", x);   global printf() also works.

#include "Chip.h"

void setup() {
    chip.PA10.use_out(); // heartbeat LED
    chip.scheduler.every(500, [](){ chip.PA10.toggle(); });
}

void loop() {
    chip.scheduler.tick();
    // Serial.printf("up %lu ms\n", (unsigned long)millis());
}
